site_name: 'Witnet Protocol Documentation'
site_url: https://docs.witnet.io
copyright: © 2018-2019 The Witnet Community. Available under <a href="https://www.gnu.org/licenses/fdl-1.3.en.html" rel="license">GNU Free Documentation License v1.3</a>

nav:
  - Overview:
      - Ecosystem: index.md
      - What is Witnet?: overview/concepts.md
      - Software: overview/software.md
  - Quickstart:
      - Run a Node: try/run-a-node.md
      - Use the Sheikah wallet / IDE: try/sheikah.md
      - Connect your Ethereum contract to an API: try/use-from-ethereum.md
  - Tutorials:
      - "Beginner: Bitcoin price feed":
        - try/my-first-data-request.md
      - "Advanced: ":
        - try/my-first-data-request.md
  - Community:
      - Contributing: community/contributing.md
      - Open Source: community/open-source.md
      - Roadmap: community/roadmap.md
  - Protocol Docs:
      - protocol/reputation.md
      - protocol/sortition.md
      - protocol/transactions.md
      - protocol/blocks.md
      - Data Requests:
          - Overview: protocol/data-requests/overview.md
          - Encoding: protocol/data-requests/radon-encoding.md
          - Examples: protocol/data-requests/examples.md
      - protocol/serialization.md
  - Operator Docs:
      - ethereum/run-a-bridge.md
      - Compilation: witnet-rust/compiling.md
      - Configuration: witnet-rust/configuration.md
      - Command Line Interface: interfaces/cli.md
      - Witnet-Rust JSON-RPC: interfaces/json-rpc.md
      - Wallet API: interfaces/wallet-api.md
  - More:
      - overview/glossary.md

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.svg" alt="Witnet Logo'
  palette:
    primary: 'white'
    accent: 'deep-purple'

repo_name: 'witnet/documentation'
repo_url: 'https://github.com/witnet/documentation'
edit_uri: 'blob/master/docs'
remote_name: 'upstream'

extra:
  og_image: 'assets/images/logo-docs.png'
  social:
    - type: 'github'
      link: 'https://github.com/witnet'
    - type: 'reddit'
      link: 'https://reddit.com/r/witnet'
    - type: 'twitter'
      link: 'https://twitter.com/witnet_io'

extra_css:
  - 'extra.css'

extra_javascript:
  - 'extra.js'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
